#!/usr/bin/env bash
# shows the subdomain, type record and IP of the subdomain.

if [ $# -eq 2 ]
then
    query=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk -F ":" "NR==2")
    query2="$1 $2 $query"
    echo $query2 | awk '{print "The subdomain " $2 " is a " $6 " record and points to " $7}' 
elif [ $# -eq 1 ]
then
    for subdomain in "www" "lb-01" "web-01" "web-02"
    do
        query=$(dig "$subdomain"."$1" | grep -A1 'ANSWER SECTION:' | awk -F ":" "NR==2")
        query2="$1 $subdomain $query"
        echo $query2 | awk '{print "The subdomain " $2 " is a " $6 " record and points to " $7}'     
    done
fi
