#!/usr/bin/env bash
# This script install nginx on the web-01 server
# Nginx should be listening on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
