#!/usr/bin/env bash
# This script allows configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
