#!/usr/bin/env bash
# This script allows configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "13 add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
