#!/usr/bin/env bash
# This script allows configure web-02 to be identical to web-01
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 3359-web-01 34.138.250.25:80 check
   server 3359-web-02 50.17.152.241:80 check check" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
