#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# h: hours from 0 to 12
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    # m: mnutes from 1 to 59
    m=1
    while [ $m -le 59 ]
    do
        echo "$m"
        (( m++ ))
    done
    (( h++ ))
done
