#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 777 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default_server
pkill apache2
sudo -u nginx service nginx restart
